spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/tiatus
    username: tiatus
    password: tiatus
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: classpath:/public,file:/Users/johnreynolds/tiatus
logging:
  file:
    name: server.log
  level:
      org:
        tiatus: DEBUG
      root: DEBUG
tiatus:
  files: /Users/johnreynolds/tiatus