spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/tiatus
    username: tiatus
    password: tiatus
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true