spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/tiatus
    username: tiatus
    password: tiatus
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
      org:
        tiatus: DEBUG
      root: DEBUG
tiatus:
  files: /Users/johnreynolds/tiatus